name: CI

on:
  push:
    branches:
    - main
    - release/*

jobs:
  deploy:
    image: node:latest
    stage: deploy
    before_script:
        - npm install netlify-cli
    script:
        - npx netlify deploy --dir public

      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
